# Generated by Django 5.0.2 on 2024-03-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="products",
            new_name="product",
        ),
    ]
