# Generated by Django 5.0.2 on 2024-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="auth_provider",
            field=models.CharField(default="email", max_length=255),
        ),
    ]
