# Generated by Django 5.0.2 on 2024-02-29 19:56

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True, upload_to=shop.models.movie_image_file_path
            ),
        ),
    ]
