# Generated by Django 5.0.2 on 2024-02-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_slug_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default=1, editable=False, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
