# Generated by Django 5.0.2 on 2024-03-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="fabric",
            new_name="materials",
        ),
    ]
