# Generated by Django 5.0.2 on 2024-03-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_rename_fabric_product_materials"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Materials",
            new_name="Material",
        ),
    ]
