# Generated by Django 5.0.2 on 2024-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_rename_materials_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.PositiveIntegerField(),
        ),
    ]
