# Generated by Django 5.0.2 on 2024-03-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_product_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["id"]},
        ),
    ]
