# Generated by Django 5.0.2 on 2024-04-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_productimage_image"),
        ("shop", "0012_alter_productimage_options"),
    ]

    operations = []
