# Generated by Django 5.0.2 on 2024-04-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_merge_20240403_1856"),
        ("shop", "0013_merge_20240410_1206"),
        ("shop", "0013_merge_20240411_1407"),
    ]

    operations = []
