# Generated by Django 5.0.2 on 2024-04-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_warehouse",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
